# Generated by Django 4.1.1 on 2022-11-01 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('keywords', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=50)),
                ('address', models.CharField(blank=True, max_length=150)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('fax', models.CharField(blank=True, max_length=15)),
                ('email', models.CharField(blank=True, max_length=50)),
                ('smptpserver', models.CharField(blank=True, max_length=30)),
                ('smptemail', models.CharField(blank=True, max_length=30)),
                ('smptpassword', models.CharField(blank=True, max_length=150)),
                ('smptport', models.CharField(blank=True, max_length=15)),
                ('icon', models.ImageField(blank=True, upload_to='images/')),
                ('facebook', models.CharField(blank=True, max_length=50)),
                ('instagram', models.CharField(blank=True, max_length=50)),
                ('twitter', models.CharField(blank=True, max_length=50)),
                ('aboutus', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=50)),
                ('contact_map', models.CharField(max_length=50)),
                ('references', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('True', 'Evet'), ('False', 'Hayır')], max_length=10)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('uptade_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
